/**
 * @license
 * Copyright Furcata. All Rights Reserved.
 */
import {BaseFirestore} from '../interface/base_db.js';

/**
 * Namespace for post models representing social-media content items (e.g.,
 * Instagram reels, YouTube videos, TikToks) that are imported, curated, and
 * optionally enriched with ML metadata before being stored in Firestore.
 *
 * Cloud Functions fetch external post data using the `source` URL or
 * platform-specific ID, populate ML fields via an AI enrichment pipeline, and
 * persist the result as a `Post.Interface` document.
 */
export namespace Post {
  /**
   * Lifecycle status of a post document within the Furcata platform.
   *
   * Cloud Functions use this value to determine whether a post should be
   * displayed to end-users or removed from listing results.
   */
  export enum Status {
    pending = 'pending',
    active = 'active',
    removed = 'removed',
    // The user should pause the account to be able to stop the queue
    unknown = 'unknown',
  }

  /**
   * Social-media platform or link type from which the post originates.
   *
   * The `type` value drives which fetcher implementation Cloud Functions use
   * to retrieve and normalise external metadata.
   */
  export enum Type {
    instagram = 'instagram',
    link = 'link',
    youtube = 'youtube',
    x = 'x',
    tiktok = 'tiktok',
    vimeo = 'vimeo',
  }

  /**
   * Firestore document shape for a single social-media post.
   *
   * Extends {@link BaseFirestore} for standard auditing fields. Cloud Functions
   * populate this document by fetching external platform metadata, running the
   * ML enrichment pipeline, and writing the result. Updates to `status` or ML
   * fields may trigger further Cloud Function listener logic.
   */
  export interface Interface extends BaseFirestore {
    /**
     * Firestore document ID of the account that owns this post.
     */
    account?: string;
    /**
     * Identifier of the service configuration used to fetch this post (e.g.,
     * a Furcata service document ID).
     */
    service?: string;
    /**
     * Source URL or platform-specific content identifier, interpreted
     * according to the `type` field.
     */
    // Source URL or id depending on the type
    source: string;
    /**
     * Current lifecycle status of the post; see {@link Status} for accepted
     * values.
     */
    status?: Status;
    /**
     * Platform origin of the post; see {@link Type} for accepted values.
     */
    type: Type;
    /**
     * Firebase Auth UID of the user who added this post to the platform.
     */
    uid?: string;
    /**
     * Content category label assigned to this post for filtering and
     * discovery purposes.
     */
    category?: string;
    /**
     * Human-readable description of the post, either sourced from the
     * external platform or provided by the curator.
     */
    description?: string;
    /**
     * When `true`, this post has been manually marked as featured and will
     * receive priority placement in listing results.
     */
    featured?: boolean;
    /**
     * Curator-assigned tags used for internal categorisation and search.
     */
    tags?: string[];
    /**
     * Hashtags associated with this post, either extracted from the source
     * platform or generated by the ML pipeline.
     */
    hashtags?: string[];
    /**
     * URL of the primary featured image for this post.
     */
    // Featured Image
    image?: string;
    /**
     * URLs of all images extracted from this post (e.g., carousel items).
     */
    // All images
    images?: string[];
    /**
     * BCP 47 language tag detected or assigned for this post's content
     * (e.g., `"en"`, `"es"`).
     */
    language?: string;
    /**
     * URL of the primary media asset (video or audio) for this post.
     */
    media?: string;
    /**
     * When `true`, the content has been reviewed and is considered safe for
     * all audiences.
     */
    safe?: boolean;
    /**
     * Title of the post, either sourced from the external platform or
     * provided by the curator.
     */
    title?: string;
    /**
     * Canonical or resolved final URL for the post, used for link previews and
     * sharing.
     */
    // Final URL
    url?: string;
    /**
     * Firebase Auth UID of the originating content creator on the external
     * platform, if resolvable.
     */
    user?: string;
    /**
     * When `true`, this post has been processed by the ML enrichment pipeline.
     */
    // ML
    ml?: boolean;
    /**
     * ML-generated title suggestion for the post.
     */
    mlTitle?: string;
    /**
     * ML-generated description suggestion for the post.
     */
    mlDescription?: string;
    /**
     * ML-generated hashtag suggestions for the post.
     */
    mlHashtags?: string[];
    /**
     * ML-selected or generated featured image URL for the post.
     */
    mlImage?: string;
    /**
     * When `true`, the external platform metadata for this post has been
     * successfully fetched and stored.
     */
    fetched?: boolean;
    /**
     * Cumulative view count for this post within the Furcata platform.
     */
    views?: number;
    /**
     * Cumulative like count for this post within the Furcata platform.
     */
    likes?: number;
  }
}
