/**
 * @license
 * Copyright Furcata. All Rights Reserved.
 */
import {z} from 'zod';
import {BaseFirestore, baseFirestoreShape} from '../interface/base_db.js';
import {
  AssertSchemaOutput,
  counter,
  documentId,
  nonEmptyString,
  ParseResult,
  parseOrThrow,
  parseResult,
} from '../interface/schema.js';

/**
 * Namespace for post models representing social-media content items (e.g.,
 * Instagram reels, YouTube videos, TikToks) that are imported, curated, and
 * optionally enriched with ML metadata before being stored in Firestore.
 *
 * Cloud Functions fetch external post data using the `source` URL or
 * platform-specific ID, populate ML fields via an AI enrichment pipeline, and
 * persist the result as a `Post.Interface` document.
 */
export namespace Post {
  /**
   * Lifecycle status of a post document within the Furcata platform.
   *
   * Cloud Functions use this value to determine whether a post should be
   * displayed to end-users or removed from listing results.
   */
  export enum Status {
    pending = 'pending',
    active = 'active',
    removed = 'removed',
    // The user should pause the account to be able to stop the queue
    unknown = 'unknown',
  }

  /**
   * Social-media platform or link type from which the post originates.
   *
   * The `type` value drives which fetcher implementation Cloud Functions use
   * to retrieve and normalise external metadata.
   */
  export enum Type {
    instagram = 'instagram',
    link = 'link',
    youtube = 'youtube',
    x = 'x',
    tiktok = 'tiktok',
    vimeo = 'vimeo',
  }

  /**
   * Firestore document shape for a single social-media post.
   *
   * Extends {@link BaseFirestore} for standard auditing fields. Cloud Functions
   * populate this document by fetching external platform metadata, running the
   * ML enrichment pipeline, and writing the result. Updates to `status` or ML
   * fields may trigger further Cloud Function listener logic.
   */
  export interface Interface extends BaseFirestore {
    /**
     * Firestore document ID of the account that owns this post.
     */
    account?: string | null;
    /**
     * Identifier of the service configuration used to fetch this post (e.g.,
     * a Furcata service document ID).
     */
    service?: string | null;
    /**
     * Source URL or platform-specific content identifier, interpreted
     * according to the `type` field.
     */
    // Source URL or id depending on the type
    source: string;
    /**
     * Current lifecycle status of the post; see {@link Status} for accepted
     * values.
     */
    status?: Status | null;
    /**
     * Platform origin of the post; see {@link Type} for accepted values.
     */
    type: Type;
    /**
     * Firebase Auth UID of the user who added this post to the platform.
     */
    uid?: string | null;
    /**
     * Content category label assigned to this post for filtering and
     * discovery purposes.
     */
    category?: string | null;
    /**
     * Human-readable description of the post, either sourced from the
     * external platform or provided by the curator.
     */
    description?: string | null;
    /**
     * When `true`, this post has been manually marked as featured and will
     * receive priority placement in listing results.
     */
    featured?: boolean | null;
    /**
     * Curator-assigned tags used for internal categorisation and search.
     */
    tags?: string[] | null;
    /**
     * Hashtags associated with this post, either extracted from the source
     * platform or generated by the ML pipeline.
     */
    hashtags?: string[] | null;
    /**
     * URL of the primary featured image for this post.
     */
    // Featured Image
    image?: string | null;
    /**
     * URLs of all images extracted from this post (e.g., carousel items).
     */
    // All images
    images?: string[] | null;
    /**
     * BCP 47 language tag detected or assigned for this post's content
     * (e.g., `"en"`, `"es"`).
     */
    language?: string | null;
    /**
     * URL of the primary media asset (video or audio) for this post.
     */
    media?: string | null;
    /**
     * When `true`, the content has been reviewed and is considered safe for
     * all audiences.
     */
    safe?: boolean | null;
    /**
     * Title of the post, either sourced from the external platform or
     * provided by the curator.
     */
    title?: string | null;
    /**
     * Canonical or resolved final URL for the post, used for link previews and
     * sharing.
     */
    // Final URL
    url?: string | null;
    /**
     * Firebase Auth UID of the originating content creator on the external
     * platform, if resolvable.
     */
    user?: string | null;
    /**
     * When `true`, this post has been processed by the ML enrichment pipeline.
     */
    // ML
    ml?: boolean | null;
    /**
     * ML-generated title suggestion for the post.
     */
    mlTitle?: string | null;
    /**
     * ML-generated description suggestion for the post.
     */
    mlDescription?: string | null;
    /**
     * ML-generated hashtag suggestions for the post.
     */
    mlHashtags?: string[] | null;
    /**
     * ML-selected or generated featured image URL for the post.
     */
    mlImage?: string | null;
    /**
     * When `true`, the external platform metadata for this post has been
     * successfully fetched and stored.
     */
    fetched?: boolean | null;
    /**
     * Cumulative view count for this post within the Furcata platform.
     */
    views?: number | null;
    /**
     * Cumulative like count for this post within the Furcata platform.
     */
    likes?: number | null;
  }

  /**
   * Runtime schema producing {@link Interface}.
   *
   * Both discriminants are validated rather than asserted. {@link Interface.type}
   * selects which external fetcher runs, so an unrecognised value is a dispatch
   * failure rather than a cosmetic one, and {@link Interface.status} gates
   * whether the post is shown to end-users, so a value that is neither
   * `removed` nor a known state fails open and displays content that was meant
   * to be withdrawn.
   *
   * Unknown keys are preserved, matching the index signature inherited from
   * {@link BaseFirestore}.
   */
  export const Schema = z.looseObject({
    ...baseFirestoreShape,
    /**
     * See {@link Interface.account}.
     */
    account: documentId().nullish(),
    /**
     * See {@link Interface.service}.
     */
    service: nonEmptyString().nullish(),
    /**
     * See {@link Interface.source}. Required: a post with no source URL or
     * platform identifier cannot be fetched or de-duplicated.
     */
    source: nonEmptyString(),
    /**
     * See {@link Interface.status}.
     */
    status: z.enum(Status).nullish(),
    /**
     * See {@link Interface.type}. Required and enum-constrained.
     */
    type: z.enum(Type),
    /**
     * See {@link Interface.uid}.
     */
    uid: nonEmptyString().nullish(),
    /**
     * See {@link Interface.category}.
     */
    category: z.string().nullish(),
    /**
     * See {@link Interface.description}.
     */
    description: z.string().nullish(),
    /**
     * See {@link Interface.featured}.
     */
    featured: z.boolean().nullish(),
    /**
     * See {@link Interface.tags}.
     */
    tags: z.array(z.string()).nullish(),
    /**
     * See {@link Interface.hashtags}.
     */
    hashtags: z.array(z.string()).nullish(),
    /**
     * See {@link Interface.image}.
     */
    image: nonEmptyString().nullish(),
    /**
     * See {@link Interface.images}.
     */
    images: z.array(z.string()).nullish(),
    /**
     * See {@link Interface.language}.
     */
    language: nonEmptyString().nullish(),
    /**
     * See {@link Interface.media}.
     */
    media: nonEmptyString().nullish(),
    /**
     * See {@link Interface.safe}.
     */
    safe: z.boolean().nullish(),
    /**
     * See {@link Interface.title}.
     */
    title: z.string().nullish(),
    /**
     * See {@link Interface.url}.
     */
    url: nonEmptyString().nullish(),
    /**
     * See {@link Interface.user}.
     */
    user: nonEmptyString().nullish(),
    /**
     * See {@link Interface.ml}.
     */
    ml: z.boolean().nullish(),
    /**
     * See {@link Interface.mlTitle}.
     */
    mlTitle: z.string().nullish(),
    /**
     * See {@link Interface.mlDescription}.
     */
    mlDescription: z.string().nullish(),
    /**
     * See {@link Interface.mlHashtags}.
     */
    mlHashtags: z.array(z.string()).nullish(),
    /**
     * See {@link Interface.mlImage}.
     */
    mlImage: nonEmptyString().nullish(),
    /**
     * See {@link Interface.fetched}.
     */
    fetched: z.boolean().nullish(),
    /**
     * See {@link Interface.views}.
     */
    views: counter().nullish(),
    /**
     * See {@link Interface.likes}.
     */
    likes: counter().nullish(),
  });

  /**
   * Compile-time proof that {@link Schema} produces {@link Interface}.
   */
  export type SchemaOutput = AssertSchemaOutput<z.infer<typeof Schema>, Interface>;

  /**
   * Validates untrusted data as a post document without throwing.
   *
   * @param {unknown} value - Untrusted value, typically the raw data of a stored post document.
   * @return {ParseResult<Interface>} Success carrying the typed post, or failure carrying the reasons.
   */
  export const safeParse = (value: unknown): ParseResult<Interface> => parseResult(Schema, value, 'Post.Interface');

  /**
   * Validates untrusted data as a post document, throwing when it does not
   * conform.
   *
   * @param {unknown} value - Untrusted value, typically the raw data of a stored post document.
   * @return {Interface} The validated post document.
   * @throws {ParseError} When the value does not conform to {@link Schema}.
   */
  export const parse = (value: unknown): Interface => parseOrThrow(Schema, value, 'Post.Interface');
}
